### ISSUE TITLE
Unable to create static site; jsdom fails

### ISSUE THREAD

**Issue by sdressler** [jessevdk/cldoc#102]
I'm trying to generate documentation for several (109) files. Generation itself works, however when I switch on `--static`, I get the following error at the very end:

```
/home/sebastian/.local/lib/python2.7/site-packages/cldoc/node_modules/jsdom/lib/jsdom.js:42
  if (options.parsingMode === undefined || options.parsingMode === 'auto') {
             ^
TypeError: Cannot read property 'parsingMode' of null
    at Object.exports.jsdom (/home/sebastian/.local/lib/python2.7/site-packages/cldoc/node_modules/jsdom/lib/jsdom.js:42:14)
    at Object.<anonymous> (/home/sebastian/.local/lib/python2.7/site-packages/cldoc/data/staticsite/staticsite.js:48:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
```

The version of `jsdom` I use is `3.1.2`. Unfortunately it is not documented which version to use. Therefore, I installed the last one suppoerted by Node.js (the author says everything `>= 4.0.0` requires io.js).

**Comment by jessevdk** [comment]
I have 3.1.2 installed, and this doesn't happen for me. That error should occur when explicitly passing in `null` for options. This got fixed in https://github.com/jessevdk/cldoc/commit/9648e3f42906f184f9019a65d75214d2fca320bb. Can you try installing and running cldoc from master?

I'm going to make static site generation more robust, and also fix the dependency issues by creating a `cldoc-static` npm package. This should avoid problems in the future. Once finished I'll publish a new version of cldoc.

**Comment by jessevdk** [comment]
I've pushed a new version of cldoc (1.8) and the accompanying cldoc-static tool as a module on npm. This should resolve the problem that you are seeing. Can you verify that you no longer have this issue?

**Comment by sdressler** [comment]
Thanks for the quick support. I updated to 1.8 and installed cldoc-static. I could successfully generate the static page.
