### ISSUE TITLE
Keep the source code's order

### ISSUE THREAD

**Issue by CorneliusCasa** [jessevdk/cldoc#70]
Currently C++ methods of a given class are sorted alphabetically.

This removes information that I put in my source code, since I manually order my methods in a meaningful way.

It would be great if cldoc could keep the original order.

**Comment by jessevdk** [comment]
Keeping the original order results in arbitrary ordering since most people don't actually take care of this. If you try to lookup documentation, alphabetical order helps much more than arbitrary categories since it will be easy to find what you are looking for. This is an explicit design choice of cldoc.
